language:
  ruby

rvm:
  2.3.0-p0

env:
  – DB=sqlite
  – DB=postgresql

before_script: psql -c 'create database issues_test;' -U postgres

script: RAILS_ENV=test bundle exec rake --trace db:schema:load db:migrate spec
