version: '2'

services:
  db:
    image: postgres:9
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB: postgresql
