version: '2'

services:
  db:
    image: postgres:9-alpine
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data/pg
    env_file: .env

  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    env_file: .env
