sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

postgresql: &postgresql
  adapter: postgresql
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: issues_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 16
  timeout: 5000
  host: issues_db_1
  <<: *<%= p ENV['DB'] || 'sqlite' %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
